version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  
  accountownerapp:
    depends_on:
      - db
    image: localhost:50000/chayana/accountowner:build-${BUILD_NUMBER_ACCOUNTOWNER}

  
  integration:
    depends_on:
      - accountownerapp
    image: localhost:50000/chayana/accountowner:test
    build:
      context: .
      dockerfile: Dockerfile.Integration
    environment:
      - TEAMCITY_PROJECT_NAME
 
      
volumes:
    dbdata: